### ISSUE TITLE
Potential issue with carry-over grades 

### ISSUE THREAD

**Issue by nightpool** [slang-legacy/webgrader-fixed#1]
Some classes, like my calc class, show grades in webgrader from last quarter but they don't count towards your grade or something? There's something screwy with them. I'll put a screenshot up here later when I can. The percentage of total graphs are WAY off.

**Comment by nightpool** [comment]
Standard:
![](http://i.imgur.com/eE09f.png?0)

Webgrader-fixed:
![](http://i.imgur.com/60crH.png?1)

**Comment by nightpool** [comment]
I think this might be a problem related to #3. Summative seems to come before formative, while webgrader-fixed assumes its always summative then formative.

**Comment by notslang** [comment]
ugh... I was worried about this. When I wrote the code which gets all the assignments out of the page, I was really lazy and just made it assume that the 1st table was formative, and 2nd is summative... also assuming the percentages are 10% and 90%. I was hoping that this was a standard thing baked into webgrader, but I guess it isn't :(

So to fix it, I just need to rewrite the scraper portion to check the title of the table (wherever, in webgrader's `<table>`-soup, _that_ is)... then probably just use a regex like `/([0-9]*%)$/` to get the percent out of it.

...then I just need to rewrite a small part that assigns the correct percentages to each assignment, but that part should be easy.

Thankfully, the latest version of the plugin has automatic updates setup, so distributing the fix will be easy.

**Comment by nightpool** [comment]
I was thinking of re-writing it with beautiful soup as a stand-alone python application or web-based server-side calculations. This would help with scraping.

**Comment by notslang** [comment]
Scraping is actually really easy... it's just JS running on the page, which has full DOM access. Also, since it's a chrome app, it has no cross-platform issues, doesn't have any dependencies, doesn't require hosting, doesn't need pages to be downloaded, and doesn't need to deal with webgrader's authentication... it doesn't even need to prompt the user for a password, it just modifies the page

However, if you really do want to write it in python, I already wrote code to deal with webgrader's authentication (before I realized that a chrome plugin would be easier), so i'll give you that code if you want it.

**Comment by notslang** [comment]
closed... same as #3
