### ISSUE TITLE
Port extension to BabelExt

### ISSUE THREAD

**Issue by nightpool** [slang-legacy/webgrader-fixed#4]
[BabelExt](github.com/honestbleeps/BabelExt) is a cross-browser framework for developing userscript type extensions. It was created for the [Reddit Enhancement Suite](http://redditenhancementsuite.com/) plugin, which sees heavy use from the Reddit set.

**Comment by nightpool** [comment]
Actually, just porting this to a greasemonkey-style user script will allow it to be recognized by chrome. JS-Only extensions are recommend to use this format.

**Comment by notslang** [comment]
this originally was a grease-monkey script... i just changed to using the chrome plugin format afterwards. anyway, I doubt that I'll be developing this any further since i'm graduating in a few days. also, I heard they are moving to blackboard for grading anyway, so it would need to be totally rewritten

**Comment by nightpool** [comment]
I was planning on developing it more myself. I haven't heard anything about
blackboard.

**Comment by notslang** [comment]
oh, cool! implementing that grade REPL?

**Comment by nightpool** [comment]
Yeah. Seems like it'd be useful next year.
