### ISSUE TITLE
Support for more weight divisions

### ISSUE THREAD

**Issue by hexane360** [slang-legacy/webgrader-fixed#5]
In some classes, my teachers thought it would be a good idea to make formatives 0.1%, notebook grades 9.9%, and summative 90%. Here is a screenshot when I try to view that class:

![webgrader](https://f.cloud.github.com/assets/3290270/73091/f2ea3470-602f-11e2-9057-2fefc503de1a.png)

Could you please add support for more grade divisions?

**Comment by notslang** [comment]
are you using version 1.4? (you can check at chrome://chrome/extensions/)

**Comment by hexane360** [comment]
Yes

I updated before I posted this

**Comment by notslang** [comment]
oh! I think I know what's wrong! I never thought about decimals being used in the percentage assigned to the grade category when I wrote the regex that finds out how much each category is worth. It's probably failing because it just checks for a "(" then numbers and then "%)" no periods... I'll fix this later tonight.

**Comment by hexane360** [comment]
thanks

**Comment by notslang** [comment]
if you update now, that should fix it. tell me if it works (since I have no good way to test it)
